# Define simulation related parameters
[Grid]
N = 500
r_min = 0.0
r_max = 1.0

[Clock]
start_time = 0.0
end_time = 1e-8
num_steps = 200


# Add the physics modules
[Modules]         
[Modules.EMWave]
amplitude = 1.0
omega = 2e8

[Modules.ChargedParticle]
position = 0.5


# Add the compute tools
[Tools]
[Tools.FiniteDifference]
method = "upwind_left"

# Empty "heading" is ok, adds the tool with no/default parameters
[Tools.BorisPush]


# Add the diagnostics
[Diagnostics]
# First add some default diagnostic parameters
directory = "output/"
output_type = "csv"

[Diagnostics.grid]
filename = "grid.csv"

[Diagnostics.clock]
filename = "time.csv"

[[Diagnostics.field]] # Double brackets here because we will have multiples of these...
component = 0
field = "EMField:E"
filename = "efield.csv"

[[Diagnostics.field]]
component = 0
field = "EMField:B"
filename = "bfield.csv"

[Diagnostics.point] # singe brackets here because we only have one of these...
field = "EMField:E"
location = 0.5
filename = "e_0.5.csv"

[[Diagnostics.ParticleDiagnostic]]
component = "momentum"
filename = "particle_p.csv"

[[Diagnostics.ParticleDiagnostic]]
component = "position"
filename = "particle_x.csv"

