# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  check-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Python Interrogate Check
        uses: JackMcKew/python-interrogate-check@v0.1.1
        with:
          # File or directory to run interrogate on.
          path: turbopy
          # Fail when coverage % is less than a given amount.
          fail-under: 80
          # Generate a `shields.io` status badge (an SVG image) in at a given file or directory.
          badge-location: . # optional, default is .
